# Generated by Django 2.2 on 2019-05-29 21:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Add_On',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('price_change', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Item_Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('price', models.FloatField(blank=True, null=True)),
                ('menu_type', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('price_change', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Menu_Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('allergy_info', models.CharField(blank=True, max_length=200, null=True)),
                ('active_status', models.CharField(default='Active', max_length=32)),
                ('min_options', models.IntegerField(default=0)),
                ('max_options', models.IntegerField(default=0)),
                ('addons', models.ManyToManyField(blank=True, to='till_sys.Add_On')),
                ('options', models.ManyToManyField(blank=True, to='till_sys.Option')),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='till_sys.Item_Type')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(blank=True, max_length=64, null=True)),
                ('dob', models.DateField()),
                ('phone', models.CharField(max_length=15)),
                ('active_status', models.CharField(default='Active', max_length=32)),
                ('date_hired', models.DateField(blank=True, null=True)),
                ('date_leave', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='Profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cart_Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.CharField(blank=True, max_length=64, null=True)),
                ('price', models.FloatField()),
                ('addons', models.ManyToManyField(blank=True, to='till_sys.Add_On')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='till_sys.Menu_Item')),
                ('options', models.ManyToManyField(blank=True, to='till_sys.Option')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.FloatField()),
                ('status', models.CharField(default='Processing', max_length=64)),
                ('time_of_order', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('items', models.ManyToManyField(blank=True, to='till_sys.Cart_Entry')),
            ],
        ),
    ]
