# Generated by Django 2.2 on 2019-06-08 07:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('till_sys', '0003_cart_entry_bread'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='time_of_order',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 8, 8, 43, 55, 198842)),
        ),
    ]
