# Generated by Django 2.2 on 2019-06-29 00:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('till_sys', '0005_auto_20190610_0512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='time_of_order',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 29, 1, 6, 26, 767481)),
        ),
    ]
