# Generated by Django 2.2 on 2019-06-29 16:21

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('till_sys', '0006_auto_20190629_0106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='time_of_order',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 29, 17, 21, 39, 964601)),
        ),
        migrations.AlterField(
            model_name='employee',
            name='active_status',
            field=models.CharField(default='Active', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='dob',
            field=models.DateField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone',
            field=models.CharField(default='', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.CharField(blank=True, default='', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(default='', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
