# Generated by Django 2.2 on 2019-06-29 16:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('till_sys', '0007_auto_20190629_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='time_of_order',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 29, 17, 24, 25, 445388)),
        ),
        migrations.AlterField(
            model_name='employee',
            name='dob',
            field=models.DateField(default='1900-01-01', null=True),
        ),
    ]
