# Generated by Django 3.0.3 on 2020-02-22 01:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Add_Ons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price_change', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bread_Types',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price_change', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cart_Entries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.CharField(blank=True, max_length=512, null=True)),
                ('price', models.FloatField()),
                ('addons', models.ManyToManyField(blank=True, to='till.Add_Ons')),
                ('bread', models.ManyToManyField(blank=True, to='till.Bread_Types')),
            ],
        ),
        migrations.CreateModel(
            name='Item_Types',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Menu_Types',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Options',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price_change', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Menu_Items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('active_status', models.CharField(default='Active', max_length=32)),
                ('addons', models.ManyToManyField(blank=True, to='till.Add_Ons')),
                ('bread_type', models.ManyToManyField(blank=True, to='till.Bread_Types')),
                ('options', models.ManyToManyField(blank=True, to='till.Options')),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='till.Item_Types')),
            ],
        ),
        migrations.AddField(
            model_name='item_types',
            name='menu_type',
            field=models.ForeignKey(max_length=32, on_delete=django.db.models.deletion.PROTECT, to='till.Menu_Types'),
        ),
        migrations.CreateModel(
            name='Carts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.FloatField()),
                ('status', models.CharField(default='Processing', max_length=64)),
                ('time_of_order', models.DateTimeField(auto_now_add=True)),
                ('payment_method', models.CharField(blank=True, max_length=64, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('entries', models.ManyToManyField(blank=True, to='till.Cart_Entries')),
            ],
        ),
        migrations.AddField(
            model_name='cart_entries',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='till.Menu_Items'),
        ),
        migrations.AddField(
            model_name='cart_entries',
            name='options',
            field=models.ManyToManyField(blank=True, to='till.Options'),
        ),
    ]
