## Populating our tables

from .models import *


## menu types
breakfast = Menu_Types(name="Breakfast")
breakfast.save()
lunch = Menu_Types(name="Lunch")
lunch.save()
drinks = Menu_Types(name="Drinks & Cakes")
drinks.save()


## item types -- categories for items, breakfst
bfast = Item_Types(name="Breakfast", menu_type=breakfast)
bfast.save()
onToast = Item_Types(name="On Toast", menu_type = breakfast)
onToast.save()
nicentoasty = Item_Types(name="Nice N Toasty", menu_type = breakfast)
nicentoasty.save()

## options
ham = Options(name="Ham")
ham.save()
cheese = Options(name="Cheese")
cheese.save()
mushrooms = Options(name="Mushrooms")
mushrooms.save()
chipspeas = Options(name="Chips & Peas")
chipspeas.save()
saladcoleslaw = Options(name="Salad with Coleslaw")
saladcoleslaw.save()
poppadom = Options(name="Poppadom")
poppadom.save()
rice = Options(name="Rice")
rice.save()
chips = Options(name="Chips")
chips.save()
mash = Options(name="Mash")
mash.save()
jacket = Options(name="Jacket")
jacket.save()
peas = Options(name="Peas")
peas.save()
beans = Options(name="Beans")
beans.save()



## bread types
white = Bread_Types(name="White")
white.save()
brown = Bread_Types(name="Brown")
brown.save()
bap = Bread_Types(name="Bap")
bap.save()
wFarmhouse = Bread_Types(name="White Farmhouse (+.50)", price_change=0.50)
wFarmhouse.save()
gFarmhouse = Bread_Types(name="Granary Farmhouse (+.50)", price_change=0.50)
gFarmhouse.save()
scone = Bread_Types(name="Cheese Scone (+.50)", price_change=0.50)
scone.save()
whiteFarmhouseNoCharge = Bread_Types(name="White Farmhouse")
whiteFarmhouseNoCharge.save()
granaryFarmhouseNoCharge = Bread_Types(name="Granary Farmhouse")
granaryFarmhouseNoCharge.save()


## Breakfast Items
one = Menu_Items(name="One Item", type=onToast, price=1.50, )
one.save()
one.options.add(ham, cheese, mushrooms)
one.bread_type.add(white, brown, wFarmhouse, gFarmhouse)
one.save()
two = Menu_Items(name="Two Items", type=onToast, price=2.50 )
two.save()
two.options.add(ham, cheese, mushrooms)
two.bread_type.add(white, brown, wFarmhouse, gFarmhouse)
two.save()
omelette = Menu_Items(name="Omellete, One Filling", type=onToast, price=4.50)
omelette.save()
omelette.options.add(cheese, ham, mushrooms)
omelette.save()
omelette2 = Menu_Items(name="Omellete, Two Fillings", type=onToast, price=5.00)
omelette2.save()
omelette.options.add(cheese, ham, mushrooms)
omelette2.save()

tbutter = Menu_Items(name="Toast & Butter, Two Slices", type=nicentoasty, price=1.50)
tbutter.save()
tbutter.bread_type.add(white, brown)
tbutter.save()
whiteFarmhouse = Menu_Items(name="White Farmhouse Toast", type=nicentoasty, price=1.00)
whiteFarmhouse.save()
granaryFarmhouse = Menu_Items(name="Granary Farmhouse Toast", type=nicentoasty, price=1.00)
granaryFarmhouse.save()
twoRounds = Menu_Items(name="Two Rounds", type=nicentoasty, price=1.75)
twoRounds.save()
teacake = Menu_Items(name="Toasted Tea Cake", type=nicentoasty, price=1.50)
teacake.save()
jam = Menu_Items(name="Jam / Marmalade", type=nicentoasty, price=0.30)
jam.save()

value = Menu_Items(name="Value Breakfast", type=bfast, price=4.00)
value.save()
value.bread_type.add(white, brown)
value.save()
mega = Menu_Items(name="Mega Breakfast", type=bfast, price=6.50)
mega.save()
mega.bread_type.add(white, brown)
mega.save()
veggiebfast = Menu_Items(name="Veggie Breakfast", type=bfast, price=4.00)
veggiebfast.save()
veggiebfast.bread_type.add(white, brown)
veggiebfast.save()
baps = Menu_Items(name="Baps & Sandwiches", type=bfast, price=2.50)
baps.save()
baps.bread_type.add(white, brown, bap)
baps.options.add(cheese, ham, mushrooms)
baps.save()


## lunch item types, categories for items
mains = Item_Types(name="Mains", menu_type=lunch)
mains.save()
favs = Item_Types(name="DC Favourites", menu_type=lunch)
favs.save()
starts = Item_Types(name="Starters & Lite Bites", menu_type=lunch)
starts.save()
small = Item_Types(name="Smaller Appetites", menu_type = lunch)
small.save()


## lunch items
haddock = Menu_Items(name="Haddock, Chips & Peas", price=6.50)
haddock.save()
cod = Menu_Items(name="Cod, Chips & Peas", price=6.50)
cod.save()
bangers = Menu_Items(name="Bangers & Mash, Onions, Gravy & Peas", price=6.50)
bangers.save()
quiche = Menu_Items(name="Quiche", price=6.50)
quiche.save()
quiche.options.add(chipspeas, saladcoleslaw)
quiche.save()
curry = Menu_Items(name="Curry", price=6.50)
curry.save()
curry.options.add(poppadom, rice, chips, jacket)
curry.save()
chilli = Menu_Items(name="Chilli Con Carne, Rice & Garlic Bread", price=6.50)
chilli.save()
chicken = Menu_Items(name="Cajun Chicken, Chips, Salad & Coleslaw", price=6.50)
chicken.save()

soup = Menu_Items(name="Soup", price=3.50)
soup.save()
soup.bread_type.add(whiteFarmhouseNoCharge, granaryFarmhouseNoCharge, scone)
soup.save()
garlicmushrooms = Menu_Items(name="Garlic Mushrooms on Farmhouse", price=3.50)
garlicmushrooms.save()
garlicmushrooms.bread_type.add(whiteFarmhouseNoCharge, granaryFarmhouseNoCharge)
garlicmushrooms.save()

smallSausage = Menu_Items(name="Small Sausage", price=4.00)
smallSausage.save()
smallSausage.options.add(mash, chips, peas, beans)
smallSausage.save()
veggieSausage = Menu_Items(name="Small Veggie Sausage", price=4.00)
veggieSausage.save()
veggieSausage.options.add(mash, chips, peas, beans)
veggieSausage.save()
smallhec = Menu_Items(name="Small Ham, Egg & Chips", price=4.00)
smallhec.save()
chickenbites = Menu_Items(name="Chicken Breast Bites, Chips & Peas", price=4.00)
chickenbites.save()
fishfingers = Menu_Items(name="Fish Fingers, Chips & Peas", price=4.00)
fishfingers.save()
smallQuiche = Menu_Items(name="Small Quiche, Salad & Coleslaw", price=4.00)
smallQuiche.save()

sausage = Menu_Items(name="Two Sausage, Egg & Chips", price=5.00)
sausage.save()
bacon = Menu_Items(name="Two Bacon, Egg & Chips", price=5.00)
bacon.save()
